# ========================================
# Application
# ========================================

# Spring Application Name
spring.application.name=auth-server

# ========================================
# Server
# ========================================

# server.address=0.0.0.0
# server.port=8080

# ========================================
# Database
# ========================================

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/chattalk_dev
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================================
# JPA (?Legacy)
# ========================================

# Entity Schema Auto Update
# spring.jpa.hibernate.ddl-auto=update

# Format SQL Output
# spring.jpa.properties.hibernate.format_sql=true

# ========================================
# MyBatis
# ========================================

# Mapper XML Location
mybatis.mapper-locations=classpath:mapper/**/*.xml

# DTO Alias Package
mybatis.type-aliases-package=com.chattalk.auth.common

# Convert Snake Case To Camel Case
mybatis.configuration.map-underscore-to-camel-case=true

# =====================================
# Logging
# =====================================

# Enable P6Spy SQL Logging
decorator.datasource.p6spy.enable-logging=true

# ========================================
# CORS ??
# ========================================

# ???
cors.allowed-origins=http://localhost:5173

# ???
# cors.allowed-origins=https://soonhlab.com